version: "3.9"

services:

  service:
    build: .
    env_file: .env
    container_name: api
    ports:
      - '3000:3000'
    environment:
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
